"""PR日本語gateの見出し判定を、workflowから実際に取り出して実行する。

既存の test_pr_japanese_workflow.py は workflow の文字列一致しか見ておらず、
判定ロジックそのものは一度も実行されていなかった。正規表現の誤りは
文字列一致では捕まらない。
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest


WORKFLOW = (
    Path(__file__).resolve().parents[2]
    / ".github"
    / "workflows"
    / "pr-japanese-gate.yml"
)


def _setext_pattern() -> re.Pattern[str]:
    """workflow に書かれている setext 正規表現を実物から取り出す。

    テスト側に写経すると、workflow を直しても test が古い式を検査し続ける。
    """
    text = WORKFLOW.read_text(encoding="utf-8")
    match = re.search(
        r'setext_headings = re\.compile\(\s*\n\s*r"([^"]+)"', text
    )
    assert match, "workflow から setext 正規表現を取り出せない"
    return re.compile(match.group(1), re.MULTILINE)


@pytest.mark.parametrize(
    ("body", "expected"),
    [
        ("見出し\n---\n", True),
        ("タイトル\n===\n", True),
        ("見出し  \n---  \n", True),
        # 空行を挟んだ水平線は下線ではない (CommonMark)。
        ("https://example.com/x\n\n---\n", False),
        ("https://example.com/x\n\n\n---\n", False),
        ("これは本文です。\n\n---\n", False),
    ],
)
def test_setext_underline_must_immediately_follow_the_paragraph(
    body: str, expected: bool
) -> None:
    assert bool(_setext_pattern().findall(body)) is expected, body


def test_pr_body_ending_with_a_url_before_a_rule_is_not_a_heading() -> None:
    """実際に落ちた形を固定する。

    PR 本文の末尾が session URL で、その後ろにサーバが `---` 付きのフッターを
    追記すると、URL が「英語だけの見出し」として拒否されていた
    (2026-09-10 実測: github-ops-skills #28)。
    """
    body = (
        "## 見つかった問題\n\n"
        "本文です。\n\n"
        "---\n"
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
        "https://claude.ai/code/session_015QUaiWUucBDAmNG2Hx2Dwb\n\n"
        "---\n"
        "_Generated by [Claude Code](https://claude.ai/code/x)_"
    )
    headings = _setext_pattern().findall(body)
    english_only = [
        h for h in headings
        if re.search(r"[A-Za-z]", h)
        and not re.search(r"[぀-ヿ㐀-鿿]", h)
    ]
    assert english_only == [], english_only
